version: "3"
services:
  web:
    image: ebm2018/irate:latest
    # depends_on:
    #   - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb/irate
    networks:
      local:
      ebm-filrouge:
        aliases:
          - irate
  # mongodb:
  #   image: mongo
  #   networks:
  #     - local
networks:
  local:
  ebm-filrouge:
    external: true
